/**
 * Language ids for file names, as VS Code assigns them (`TextDocument.languageId`). The
 * extension host reports them to the extension; the renderer picks a grammar by them.
 */

const BY_EXTENSION: Readonly<Record<string, string>> = {
  '.ts': 'typescript',
  '.mts': 'typescript',
  '.cts': 'typescript',
  '.tsx': 'typescriptreact',
  '.js': 'javascript',
  '.mjs': 'javascript',
  '.cjs': 'javascript',
  '.jsx': 'javascriptreact',
  '.json': 'json',
  '.jsonc': 'jsonc',
  '.json5': 'json5',
  '.jsonl': 'jsonl',
  '.md': 'markdown',
  '.markdown': 'markdown',
  '.mdx': 'mdx',
  '.py': 'python',
  '.pyw': 'python',
  '.pyi': 'python',
  '.ipynb': 'jupyter',
  '.c': 'c',
  '.h': 'c',
  '.cpp': 'cpp',
  '.cc': 'cpp',
  '.cxx': 'cpp',
  '.hpp': 'cpp',
  '.hh': 'cpp',
  '.hxx': 'cpp',
  '.cu': 'cuda-cpp',
  '.cs': 'csharp',
  '.fs': 'fsharp',
  '.fsx': 'fsharp',
  '.java': 'java',
  '.kt': 'kotlin',
  '.kts': 'kotlin',
  '.scala': 'scala',
  '.groovy': 'groovy',
  '.gradle': 'groovy',
  '.go': 'go',
  '.rs': 'rust',
  '.swift': 'swift',
  '.m': 'objective-c',
  '.mm': 'objective-cpp',
  '.dart': 'dart',
  '.rb': 'ruby',
  '.php': 'php',
  '.pl': 'perl',
  '.pm': 'perl',
  '.lua': 'lua',
  '.r': 'r',
  '.jl': 'julia',
  '.hs': 'haskell',
  '.clj': 'clojure',
  '.ex': 'elixir',
  '.exs': 'elixir',
  '.erl': 'erlang',
  '.zig': 'zig',
  '.vb': 'vb',
  '.html': 'html',
  '.htm': 'html',
  '.xhtml': 'html',
  '.vue': 'vue',
  '.svelte': 'svelte',
  '.astro': 'astro',
  '.css': 'css',
  '.scss': 'scss',
  '.sass': 'sass',
  '.less': 'less',
  '.xml': 'xml',
  '.xsd': 'xml',
  '.xaml': 'xml',
  '.csproj': 'xml',
  '.props': 'xml',
  '.svg': 'xml',
  '.yml': 'yaml',
  '.yaml': 'yaml',
  '.toml': 'toml',
  '.ini': 'ini',
  '.cfg': 'ini',
  '.conf': 'ini',
  '.properties': 'properties',
  '.env': 'dotenv',
  '.ps1': 'powershell',
  '.psm1': 'powershell',
  '.psd1': 'powershell',
  '.sh': 'shellscript',
  '.bash': 'shellscript',
  '.zsh': 'shellscript',
  '.bat': 'bat',
  '.cmd': 'bat',
  '.sql': 'sql',
  '.graphql': 'graphql',
  '.gql': 'graphql',
  '.proto': 'proto',
  '.tex': 'latex',
  '.bib': 'bibtex',
  '.rst': 'restructuredtext',
  '.diff': 'diff',
  '.patch': 'diff',
  '.log': 'log',
  '.csv': 'csv',
  '.tsv': 'tsv',
  '.dockerfile': 'dockerfile',
  '.tf': 'terraform',
  '.hcl': 'hcl',
  '.nix': 'nix',
  '.cmake': 'cmake',
  '.txt': 'plaintext',
};

/** Whole file names (lower case) that decide the language on their own. */
const BY_NAME: Readonly<Record<string, string>> = {
  dockerfile: 'dockerfile',
  containerfile: 'dockerfile',
  makefile: 'makefile',
  gnumakefile: 'makefile',
  'cmakelists.txt': 'cmake',
  '.gitignore': 'ignore',
  '.gitattributes': 'gitattributes',
  '.npmignore': 'ignore',
  '.editorconfig': 'properties',
  '.env': 'dotenv',
  'tsconfig.json': 'jsonc',
  'jsconfig.json': 'jsonc',
  'settings.json': 'jsonc',
  'keybindings.json': 'jsonc',
  'claude.md': 'markdown',
};

/** `languageId` for a file name or path; `plaintext` when unknown. */
export function languageIdFor(fileName: string): string {
  const base = fileName.split(/[\\/]/).pop()!.toLowerCase();
  const byName = BY_NAME[base];
  if (byName) {
    return byName;
  }
  const dot = base.lastIndexOf('.');
  if (dot > 0 || (dot === 0 && base.length > 1)) {
    return BY_EXTENSION[base.slice(dot)] ?? 'plaintext';
  }
  return 'plaintext';
}
